---
title: "Essentials of Mathematics and Statistics"
author: "Anas A Rana"
date: "`r Sys.Date()`"
bibliography:
- book.bib
description: This contains practicals for the second week of module 1 (_Essentials of Mathematics and Statistics_).
documentcalss: book
output:
    bookdown::gitbook:
        lib_dir: assets
        self_contained: true
        split_by: chapter
        config:
            toolbar:
                position: static
    bookdown::pdf_book:
        keep_tex: no
        number_sections: no
link-citations: yes
site: bookdown::gitbook
subtitle: 'Practical: Module 1'
biblio-style: apalike
url: 'https\://anasrana.github.io/module1-practical_Bham/'
github-repo: "anasrana/module1-practical_Bham"
---

# Introduction

This is part of the practical for [Module 1 - Essentials of Mathematics and Statistics](https://canvas.bham.ac.uk/courses/39247/pages/essentials-of-biology-mathematics-and-statistics) part of the [MSc Bioinformatics 2018/19](https://www.birmingham.ac.uk/postgraduate/courses/taught/med/bioinformatics.aspx) at the University of Birmingham.

This website hosts the practicals for week two of **Module 1**, which covers:

- Linear regression
- Principal Component Analysis (PCA)
- Multivariate Regression
- Generalised Linear Models

## Prerequisites

Ensure you have attended Module 1 lectures and have the installed `R` and/or `Rstudio`. `Rstudio` is recommended, any packages required for each practical are mentioned at the beginning of each practical.

## Data sets

For each practical there are some datasets required, you will find all data required for week two of practicals in the data folder [here](https://github.com/anasrana/module1-practical_Bham/tree/master/data). Links to individual datasets requried can be found at the beginning of each practical or on Canvas.
